version: "3"

services:
  web:
    container_name: exampleapp
    restart: always
    build: .
    ports:
      - "5000:3000"
    links:
      - mongo
    # volumes me este util para sincronizacion de mi docker y mi local
    volumes:
      - .:/usr/src/app
  mongo:
    container_name: mymongodatabase
    image: mongo
    ports:
      - "27018:27017"
    logging:
      # disabled of logs mongod
      driver: none